-- Create fw_user_professional table for storing worker professional data
-- Date: 2025-01-27

CREATE TABLE IF NOT EXISTS fw_user_professional (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT(20) UNSIGNED NOT NULL,
    total_experience INT(11) DEFAULT 0,
    education_level VARCHAR(100) DEFAULT NULL,
    field_of_study VARCHAR(255) DEFAULT NULL,
    institution_name VARCHAR(255) DEFAULT NULL,
    graduation_year INT(11) DEFAULT NULL,
    professional_summary TEXT DEFAULT NULL,
    specialized_skills TEXT DEFAULT NULL,
    specialized_experience TEXT DEFAULT NULL,
    key_projects TEXT DEFAULT NULL,
    previous_employers TEXT DEFAULT NULL,
    `references` TEXT DEFAULT NULL,
    availability VARCHAR(50) DEFAULT NULL,
    travel_willingness VARCHAR(50) DEFAULT NULL,
    drivers_license VARCHAR(10) DEFAULT NULL,
    red_seal VARCHAR(50) DEFAULT NULL,
    provincial_certificate VARCHAR(255) DEFAULT NULL,
    union_membership VARCHAR(255) DEFAULT NULL,
    equipment_tools TEXT DEFAULT NULL,
    whmis VARCHAR(50) DEFAULT NULL,
    first_aid VARCHAR(50) DEFAULT NULL,
    fall_protection VARCHAR(50) DEFAULT NULL,
    confined_space VARCHAR(50) DEFAULT NULL,
    lockout_tagout VARCHAR(50) DEFAULT NULL,
    other_safety TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY user_id (user_id),
    KEY idx_total_experience (total_experience),
    KEY idx_education_level (education_level),
    KEY idx_availability (availability),
    KEY idx_drivers_license (drivers_license),
    KEY idx_red_seal (red_seal),
    CONSTRAINT fk_user_professional_user_id FOREIGN KEY (user_id) REFERENCES fw_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
